/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpbo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author RyanK
 */
public class Battle extends javax.swing.JFrame {
    private ArrayList<User> u = new ArrayList<>();
    private int idx;
    
    private ArrayList<JLabel> ranger = new ArrayList<>();
    private Timer t;
    /**
     * Creates new form Battle
     */
    public Battle() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Battle(ArrayList<User> player, int idx) {
        this.u = player;
        this.idx = idx;
        initComponents();
        this.setLocationRelativeTo(null);       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btEris = new javax.swing.JButton();
        btPause = new javax.swing.JButton();
        BoxMineral = new javax.swing.JLabel();
        Ranger3 = new javax.swing.JButton();
        Ranger2 = new javax.swing.JButton();
        Ranger1 = new javax.swing.JButton();
        BoxRangers = new javax.swing.JLabel();
        HPTowerEnemy = new javax.swing.JLabel();
        HPTowerRanger = new javax.swing.JLabel();
        btTowerAtt = new javax.swing.JButton();
        TowerEnemy = new javax.swing.JLabel();
        TowerPlayer = new javax.swing.JLabel();
        BgBattle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rangers Wars");
        setLocation(new java.awt.Point(325, 180));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btEris.setText("Eris");
        btEris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btErisActionPerformed(evt);
            }
        });
        getContentPane().add(btEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 80, 70));

        btPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol Pause.png"))); // NOI18N
        btPause.setBorderPainted(false);
        btPause.setContentAreaFilled(false);
        btPause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPauseActionPerformed(evt);
            }
        });
        getContentPane().add(btPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, -1, -1));

        BoxMineral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mineral box.png"))); // NOI18N
        getContentPane().add(BoxMineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, -1, -1));

        Ranger3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Box rangers.png"))); // NOI18N
        Ranger3.setBorderPainted(false);
        Ranger3.setContentAreaFilled(false);
        getContentPane().add(Ranger3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 600, -1, -1));

        Ranger2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Box rangers.png"))); // NOI18N
        Ranger2.setBorderPainted(false);
        Ranger2.setContentAreaFilled(false);
        getContentPane().add(Ranger2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, -1, -1));

        Ranger1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Box rangers.png"))); // NOI18N
        Ranger1.setBorderPainted(false);
        Ranger1.setContentAreaFilled(false);
        getContentPane().add(Ranger1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, -1, -1));

        BoxRangers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Box untuk rangers 3.png"))); // NOI18N
        BoxRangers.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(BoxRangers, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, -1, 140));

        HPTowerEnemy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nyawa Tower Musuh.png"))); // NOI18N
        getContentPane().add(HPTowerEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 600, -1, -1));

        HPTowerRanger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nyawa tower rangers.png"))); // NOI18N
        getContentPane().add(HPTowerRanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        btTowerAtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tower Attack.png"))); // NOI18N
        btTowerAtt.setBorderPainted(false);
        btTowerAtt.setContentAreaFilled(false);
        getContentPane().add(btTowerAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, -1, -1));

        TowerEnemy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tower Musuh.png"))); // NOI18N
        getContentPane().add(TowerEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, -1, -1));

        TowerPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tower Rangers.png"))); // NOI18N
        getContentPane().add(TowerPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        BgBattle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background Habis login revisi.gif"))); // NOI18N
        getContentPane().add(BgBattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btErisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btErisActionPerformed
        ranger.add(new JLabel());
        ImageIcon troop = new ImageIcon("src\\images\\ErisJalan.gif");
        ranger.get(ranger.size()-1).setIcon(troop);
        ranger.get(ranger.size()-1).setBounds(210, 310, 200, 270);
        getContentPane().add(ranger.get(ranger.size()-1), new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1),1);
        
        ActionListener act = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                for (int i = 0; i < ranger.size(); i++) {
                    int posx = ranger.get(i).getLocation().x;
                    int posy = ranger.get(i).getLocation().y;
                    if (posx+200 < 1030){
                        ranger.get(i).setLocation(posx+1, posy);
                    }else if (posx+200 == 1030){
                        ImageIcon att = new ImageIcon("src\\images\\Eris_Attack.gif");
                        ranger.get(i).setIcon(att);
                        ranger.get(i).setBounds(730, 170, 491, 449);
                        t.stop();
                    }
                }
            }
        };
        
        if (t == null){
            t = new Timer(10, act);
            t.start();
        }
    }//GEN-LAST:event_btErisActionPerformed

    private void btPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPauseActionPerformed
        dispose();
        new Game(u, idx).setVisible(true);
    }//GEN-LAST:event_btPauseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Battle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgBattle;
    private javax.swing.JLabel BoxMineral;
    private javax.swing.JLabel BoxRangers;
    private javax.swing.JLabel HPTowerEnemy;
    private javax.swing.JLabel HPTowerRanger;
    private javax.swing.JButton Ranger1;
    private javax.swing.JButton Ranger2;
    private javax.swing.JButton Ranger3;
    private javax.swing.JLabel TowerEnemy;
    private javax.swing.JLabel TowerPlayer;
    private javax.swing.JButton btEris;
    private javax.swing.JButton btPause;
    private javax.swing.JButton btTowerAtt;
    // End of variables declaration//GEN-END:variables
}
