/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpbo;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author RyanK
 */
public class Game extends javax.swing.JFrame {
    private Music btClick = new Music("src\\music\\buttonclick.wav");
    private Music battleStart = new Music("src\\music\\BattleStart.wav");
    private Music MainTheme = null;
    private boolean kemute = false;
    private boolean keplay = false;
    
    private ArrayList<User> user = new ArrayList<>();
    private int idx;
    
    private ImageIcon btMerah = new ImageIcon("src\\images\\tombol merah.png");
    private ImageIcon btHijau = new ImageIcon("src\\images\\tombol ijo.png");
    
    /**
     * Creates new form Game
     */
    
    // Proc Saving
    private void SavingGame(){
        try {            
            FileOutputStream save = new FileOutputStream(System.getProperty("user.dir") + "\\users.ser");
            ObjectOutputStream out = new ObjectOutputStream(save);
            out.writeObject(this.user);
            out.close();
            save.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "failed");
        }
    }
    
    public Game(){
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Game(ArrayList<User> players, int idx, Music MainTheme, boolean kemute, boolean keplay) {
        this.MainTheme = MainTheme;
        this.kemute = kemute;
        this.keplay = keplay;
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.idx = idx;
        this.user = players;
        judul.setText(user.get(idx).getNama());
        Level.setText(""+user.get(idx).getLevel());
        Gold.setText("" + user.get(idx).getGold());
        
        if (user.get(idx).getChoose()[0])
            merah1.setIcon(btHijau);
        if (user.get(idx).getChoose()[1])
            merah2.setIcon(btHijau);
        if (user.get(idx).getChoose()[2])
            merah3.setIcon(btHijau);
        if (user.get(idx).getChoose()[3])
            merah4.setIcon(btHijau);
        if (user.get(idx).getChoose()[4])
            merah5.setIcon(btHijau);
        
        SavingGame();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTowerUp = new javax.swing.JButton();
        btUpgrade = new javax.swing.JButton();
        IdleShogun = new javax.swing.JLabel();
        IdleEris = new javax.swing.JLabel();
        IdleYoimiya = new javax.swing.JLabel();
        btLogout = new javax.swing.JButton();
        judul = new javax.swing.JLabel();
        btLaunch = new javax.swing.JButton();
        GoldLB = new javax.swing.JLabel();
        LevelLB = new javax.swing.JLabel();
        Level = new javax.swing.JLabel();
        Gold = new javax.swing.JLabel();
        WelcomeLB = new javax.swing.JLabel();
        merah1 = new javax.swing.JLabel();
        merah2 = new javax.swing.JLabel();
        merah3 = new javax.swing.JLabel();
        merah4 = new javax.swing.JLabel();
        merah5 = new javax.swing.JLabel();
        HeroStand = new javax.swing.JLabel();
        pilih5 = new javax.swing.JButton();
        pilih4 = new javax.swing.JButton();
        pilih3 = new javax.swing.JButton();
        pilih2 = new javax.swing.JButton();
        pilih1 = new javax.swing.JButton();
        BgGame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rangers Wars");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btTowerUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol Up Tower menu.png"))); // NOI18N
        btTowerUp.setContentAreaFilled(false);
        btTowerUp.setDefaultCapable(false);
        btTowerUp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol Up Tower Menu hovered.png"))); // NOI18N
        btTowerUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTowerUpActionPerformed(evt);
            }
        });
        getContentPane().add(btTowerUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 140, 140));

        btUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol upgrade.png"))); // NOI18N
        btUpgrade.setBorderPainted(false);
        btUpgrade.setContentAreaFilled(false);
        btUpgrade.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol upgrade Hovered.png"))); // NOI18N
        btUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btUpgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 140, 140));

        IdleShogun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Raiden Shogun Jalan Menu.gif"))); // NOI18N
        getContentPane().add(IdleShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 255, -1, -1));

        IdleEris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ErisPilih.gif"))); // NOI18N
        getContentPane().add(IdleEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 250, -1, -1));

        IdleYoimiya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/YoimiyaPilih.gif"))); // NOI18N
        getContentPane().add(IdleYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 255, -1, -1));

        btLogout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit button.png"))); // NOI18N
        btLogout.setBorderPainted(false);
        btLogout.setContentAreaFilled(false);
        btLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLogout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit button hovered.png"))); // NOI18N
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 140, 140));

        judul.setBackground(new java.awt.Color(0, 0, 0));
        judul.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setOpaque(true);
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 220, 40));

        btLaunch.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btLaunch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol Start.png"))); // NOI18N
        btLaunch.setBorderPainted(false);
        btLaunch.setContentAreaFilled(false);
        btLaunch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLaunch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol Start Hovered.png"))); // NOI18N
        btLaunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLaunchActionPerformed(evt);
            }
        });
        getContentPane().add(btLaunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 530, 190, 180));

        GoldLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GoldLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gold  _ label.png"))); // NOI18N
        getContentPane().add(GoldLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        LevelLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Level _ label.png"))); // NOI18N
        getContentPane().add(LevelLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Level.setBackground(new java.awt.Color(0, 0, 0));
        Level.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 52)); // NOI18N
        Level.setForeground(new java.awt.Color(0, 102, 255));
        Level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Level.setText("Level");
        Level.setToolTipText("");
        Level.setOpaque(true);
        getContentPane().add(Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 25, 170, 50));

        Gold.setBackground(new java.awt.Color(0, 0, 0));
        Gold.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 52)); // NOI18N
        Gold.setForeground(new java.awt.Color(255, 255, 0));
        Gold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gold.setText("Gold");
        Gold.setOpaque(true);
        getContentPane().add(Gold, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 86, 170, 50));

        WelcomeLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Welcome_label.png"))); // NOI18N
        getContentPane().add(WelcomeLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        merah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tombol merah.png"))); // NOI18N
        getContentPane().add(merah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, -1));

        merah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tombol merah.png"))); // NOI18N
        getContentPane().add(merah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        merah3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tombol merah.png"))); // NOI18N
        getContentPane().add(merah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, -1, -1));

        merah4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tombol merah.png"))); // NOI18N
        getContentPane().add(merah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, -1, -1));

        merah5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tombol merah.png"))); // NOI18N
        getContentPane().add(merah5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 490, -1, -1));

        HeroStand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bawahe Rangers.png"))); // NOI18N
        getContentPane().add(HeroStand, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        pilih5.setBorderPainted(false);
        pilih5.setContentAreaFilled(false);
        pilih5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih5ActionPerformed(evt);
            }
        });
        getContentPane().add(pilih5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 230, 180, 300));

        pilih4.setBorderPainted(false);
        pilih4.setContentAreaFilled(false);
        pilih4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih4ActionPerformed(evt);
            }
        });
        getContentPane().add(pilih4, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 230, 180, 300));

        pilih3.setBorderPainted(false);
        pilih3.setContentAreaFilled(false);
        pilih3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih3ActionPerformed(evt);
            }
        });
        getContentPane().add(pilih3, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 230, 180, 300));

        pilih2.setBorderPainted(false);
        pilih2.setContentAreaFilled(false);
        pilih2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih2ActionPerformed(evt);
            }
        });
        getContentPane().add(pilih2, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 230, 180, 300));

        pilih1.setBorderPainted(false);
        pilih1.setContentAreaFilled(false);
        pilih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih1ActionPerformed(evt);
            }
        });
        getContentPane().add(pilih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 180, 300));

        BgGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background Habis login revisi.gif"))); // NOI18N
        getContentPane().add(BgGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // Saving
        SavingGame();
        dispose();
        new Login(MainTheme, kemute, keplay).setVisible(true);
        if (!kemute){
            btClick = new Music("src\\music\\buttonclick.wav");
            btClick.Clip().start();
        }
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btLaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLaunchActionPerformed
        boolean sementara[] = user.get(idx).getChoose();
        int Choice = 0;
        for (int i = 0; i < sementara.length; i++) {
            if (sementara[i]){
                Choice++;
            }
        }
        if (Choice == 3){
            dispose();
            new Battle(user, idx, MainTheme, kemute, keplay).setVisible(true);
            if (!kemute){
                battleStart = new Music("src\\music\\BattleStart.wav");
                battleStart.Clip().start();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Harus Terpilih 3 Rangers", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btLaunchActionPerformed

    private void pilih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih1ActionPerformed
        if (user.get(idx).getChoose()[0]){
            user.get(idx).setChoose(0, false);
            merah1.setIcon(btMerah);
            if (!kemute){
                btClick = new Music("src\\music\\buttonclick.wav");
                btClick.Clip().start();
            }
        }else{
            boolean sementara[] = user.get(idx).getChoose();
            int Choice = 0;
            for (int i = 0; i < sementara.length; i++) {
                if (sementara[i]){
                    Choice++;
                }
            }
            if (Choice == 3){
                JOptionPane.showMessageDialog(null, "Harus Terpilih 3 Rangers", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{
                user.get(idx).setChoose(0, true);
                merah1.setIcon(btHijau);
                if (!kemute){
                    btClick = new Music("src\\music\\buttonclick.wav");
                    btClick.Clip().start();
                }
            }
        }
    }//GEN-LAST:event_pilih1ActionPerformed

    private void pilih2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih2ActionPerformed
        if (user.get(idx).getChoose()[1]){
            user.get(idx).setChoose(1, false);
            merah2.setIcon(btMerah);
            if (!kemute){
                btClick = new Music("src\\music\\buttonclick.wav");
                btClick.Clip().start();
            }
        }else{
            boolean sementara[] = user.get(idx).getChoose();
            int Choice = 0;
            for (int i = 0; i < sementara.length; i++) {
                if (sementara[i]){
                    Choice++;
                }
            }
            if (Choice == 3){
                JOptionPane.showMessageDialog(null, "Harus Terpilih 3 Rangers", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{
                user.get(idx).setChoose(1, true);
                merah2.setIcon(btHijau);
                if (!kemute){
                    btClick = new Music("src\\music\\buttonclick.wav");
                    btClick.Clip().start();
                }
            }
        }
    }//GEN-LAST:event_pilih2ActionPerformed

    private void pilih3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih3ActionPerformed
        if (user.get(idx).getChoose()[2]){
            user.get(idx).setChoose(2, false);
            merah3.setIcon(btMerah);
            if (!kemute){
                btClick = new Music("src\\music\\buttonclick.wav");
                btClick.Clip().start();
            }
        }else{
            boolean sementara[] = user.get(idx).getChoose();
            int Choice = 0;
            for (int i = 0; i < sementara.length; i++) {
                if (sementara[i]){
                    Choice++;
                }
            }
            if (Choice == 3){
                JOptionPane.showMessageDialog(null, "Harus Terpilih 3 Rangers", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{
                user.get(idx).setChoose(2, true);
                merah3.setIcon(btHijau);
                if (!kemute){
                    btClick = new Music("src\\music\\buttonclick.wav");
                    btClick.Clip().start();
                }
            }
        }
    }//GEN-LAST:event_pilih3ActionPerformed

    private void pilih4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih4ActionPerformed
        if (user.get(idx).getChoose()[3]){
            user.get(idx).setChoose(3, false);
            merah4.setIcon(btMerah);
            if (!kemute){
                btClick = new Music("src\\music\\buttonclick.wav");
                btClick.Clip().start();
            }
        }else{
            boolean sementara[] = user.get(idx).getChoose();
            int Choice = 0;
            for (int i = 0; i < sementara.length; i++) {
                if (sementara[i]){
                    Choice++;
                }
            }
            if (Choice == 3){
                JOptionPane.showMessageDialog(null, "Harus Terpilih 3 Rangers", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{
                user.get(idx).setChoose(3, true);
                merah4.setIcon(btHijau);
                if (!kemute){
                    btClick = new Music("src\\music\\buttonclick.wav");
                    btClick.Clip().start();
                }
            }
        }
    }//GEN-LAST:event_pilih4ActionPerformed

    private void pilih5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih5ActionPerformed
        if (user.get(idx).getChoose()[4]){
            user.get(idx).setChoose(4, false);
            merah5.setIcon(btMerah);
            if (!kemute){
                btClick = new Music("src\\music\\buttonclick.wav");
                btClick.Clip().start();
            }
        }else{
            boolean sementara[] = user.get(idx).getChoose();
            int Choice = 0;
            for (int i = 0; i < sementara.length; i++) {
                if (sementara[i]){
                    Choice++;
                }
            }
            if (Choice == 3){
                JOptionPane.showMessageDialog(null, "Harus Terpilih 3 Rangers", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{
                user.get(idx).setChoose(4, true);
                merah5.setIcon(btHijau);
                if (!kemute){
                    btClick = new Music("src\\music\\buttonclick.wav");
                    btClick.Clip().start();
                }
            }
        }
    }//GEN-LAST:event_pilih5ActionPerformed

    private void btUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpgradeActionPerformed
        // TODO add your handling code here:
        dispose();
        new Upgrade(user, idx, MainTheme, kemute, keplay).setVisible(true);
        if (!kemute){
            btClick = new Music("src\\music\\buttonclick.wav");
            btClick.Clip().start();
        }
    }//GEN-LAST:event_btUpgradeActionPerformed

    private void btTowerUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTowerUpActionPerformed
        dispose();
        new TowerUp(user, idx, MainTheme, kemute, keplay).setVisible(true);
        if (!kemute){
            btClick = new Music("src\\music\\buttonclick.wav");
            btClick.Clip().start();
        }
    }//GEN-LAST:event_btTowerUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgGame;
    private javax.swing.JLabel Gold;
    private javax.swing.JLabel GoldLB;
    private javax.swing.JLabel HeroStand;
    private javax.swing.JLabel IdleEris;
    private javax.swing.JLabel IdleShogun;
    private javax.swing.JLabel IdleYoimiya;
    private javax.swing.JLabel Level;
    private javax.swing.JLabel LevelLB;
    private javax.swing.JLabel WelcomeLB;
    private javax.swing.JButton btLaunch;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btTowerUp;
    private javax.swing.JButton btUpgrade;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel merah1;
    private javax.swing.JLabel merah2;
    private javax.swing.JLabel merah3;
    private javax.swing.JLabel merah4;
    private javax.swing.JLabel merah5;
    private javax.swing.JButton pilih1;
    private javax.swing.JButton pilih2;
    private javax.swing.JButton pilih3;
    private javax.swing.JButton pilih4;
    private javax.swing.JButton pilih5;
    // End of variables declaration//GEN-END:variables
}
