/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpbo;

import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author Grady
 */
public class Leaderboard extends javax.swing.JFrame {
    private ArrayList<User> user;
    /**
     * Creates new form Leaderboard
     */
    public Leaderboard() {
        initComponents();
    }
    
    public Leaderboard(ArrayList<User> player) {
        this.user = player;
        Collections.sort(user, new SortLeader());
        initComponents();
        
        if (user.get(0) != null){
            nomor1.setText(user.get(0).getNama() + " - " + user.get(0).getLevel());
        }else{
            nomor1.setText("-");
        }
        if (user.get(1) != null){
            nomor2.setText(user.get(1).getNama() + " - " + user.get(1).getLevel());
        }else{
            nomor2.setText("-");
        }
        if (user.get(0) != null){
            nomor3.setText(user.get(2).getNama() + " - " + user.get(2).getLevel());
        }else{
            nomor3.setText("-");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Leaderboard = new javax.swing.JLabel();
        nomor1 = new javax.swing.JLabel();
        nomor2 = new javax.swing.JLabel();
        nomor3 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 720));
        getContentPane().setLayout(null);

        Leaderboard.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        Leaderboard.setText("Leaderboard");
        getContentPane().add(Leaderboard);
        Leaderboard.setBounds(400, 120, 402, 97);

        nomor1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nomor1.setText("Player 1");
        getContentPane().add(nomor1);
        nomor1.setBounds(490, 280, 230, 40);

        nomor2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nomor2.setText("Player 2");
        getContentPane().add(nomor2);
        nomor2.setBounds(490, 340, 230, 40);

        nomor3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nomor3.setText("Player 3");
        getContentPane().add(nomor3);
        nomor3.setBounds(490, 400, 230, 40);

        Back.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(510, 550, 175, 58);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaderboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Leaderboard;
    private javax.swing.JLabel nomor1;
    private javax.swing.JLabel nomor2;
    private javax.swing.JLabel nomor3;
    // End of variables declaration//GEN-END:variables
}
