/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpbo;

import java.util.ArrayList;

/**
 *
 * @author Grady
 */
public class Upgrade extends javax.swing.JFrame {
    private Music player = null;
    private boolean kemute = false;
    private boolean keplay = false;
    
    private ArrayList<User> pemain = new ArrayList<>();
    private int idx;
    
    private int curGold;
    private int costEris;
    private int costYoimiya;
    private int costShogun;
    /**
     * Creates new form Upgrade
     */
    public Upgrade() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Upgrade(ArrayList<User> pemain,int idx, Music player, boolean kemute, boolean keplay) {
        this.player = player;
        this.kemute = kemute;
        this.keplay = keplay;
        
        this.pemain=pemain;
        this.idx=idx;
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.curGold = pemain.get(idx).getGold();
        gold.setText(Integer.toString(curGold));
        user.setText(pemain.get(idx).getNama());
        
        hpEris.setText(Integer.toString(pemain.get(idx).getRanger()[0].getHp()));
        dmgEris.setText(Integer.toString(pemain.get(idx).getRanger()[0].getDmg()));
        int levelEris = pemain.get(idx).getRanger()[0].getLevel();
        lvlEris.setText("Level " + Integer.toString(levelEris));
        costEris = 5 + (levelEris-1)*10;
        hargaEris.setText(Integer.toString(costEris));
                
        hpYoimiya.setText(Integer.toString(pemain.get(idx).getRanger()[1].getHp()));
        dmgYoimiya.setText(Integer.toString(pemain.get(idx).getRanger()[1].getDmg()));
        int levelYoimiya = pemain.get(idx).getRanger()[1].getLevel();
        lvlYoimiya.setText("Level " + Integer.toString(levelYoimiya));
        costYoimiya = 5 + (levelYoimiya-1)*10;
        hargaYoimiya.setText(Integer.toString(costYoimiya));
        
        hpShogun.setText(Integer.toString(pemain.get(idx).getRanger()[2].getHp()));
        dmgShogun.setText(Integer.toString(pemain.get(idx).getRanger()[2].getDmg()));
        int levelShogun = pemain.get(idx).getRanger()[2].getLevel();
        lvlShogun.setText("Level " + Integer.toString(levelShogun));
        costShogun = 5 + (levelShogun-1)*10;
        hargaShogun.setText(Integer.toString(costShogun));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MineralYoi = new javax.swing.JLabel();
        MineralShogun = new javax.swing.JLabel();
        ARROWUP2 = new javax.swing.JLabel();
        hargaShogun = new javax.swing.JLabel();
        lvlShogun = new javax.swing.JLabel();
        upShogun = new javax.swing.JButton();
        dmgShogun = new javax.swing.JLabel();
        hpShogun = new javax.swing.JLabel();
        ARROWUP1 = new javax.swing.JLabel();
        hargaYoimiya = new javax.swing.JLabel();
        lvlYoimiya = new javax.swing.JLabel();
        upYoimiya = new javax.swing.JButton();
        dmgYoimiya = new javax.swing.JLabel();
        hpYoimiya = new javax.swing.JLabel();
        ARROWUP = new javax.swing.JLabel();
        hargaEris = new javax.swing.JLabel();
        lvlEris = new javax.swing.JLabel();
        upEris = new javax.swing.JButton();
        dmgEris = new javax.swing.JLabel();
        hpEris = new javax.swing.JLabel();
        MineralEris = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        gold = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        BgUpgrade = new javax.swing.JLabel();
        dmgEris1 = new javax.swing.JLabel();
        dmgEris2 = new javax.swing.JLabel();
        dmgEris3 = new javax.swing.JLabel();
        dmgEris4 = new javax.swing.JLabel();
        dmgEris5 = new javax.swing.JLabel();
        dmgEris6 = new javax.swing.JLabel();
        dmgEris7 = new javax.swing.JLabel();
        dmgEris8 = new javax.swing.JLabel();
        dmgEris9 = new javax.swing.JLabel();
        dmgEris10 = new javax.swing.JLabel();
        dmgEris11 = new javax.swing.JLabel();
        dmgEris12 = new javax.swing.JLabel();
        dmgEris13 = new javax.swing.JLabel();
        dmgEris14 = new javax.swing.JLabel();
        dmgEris15 = new javax.swing.JLabel();
        dmgEris16 = new javax.swing.JLabel();
        dmgEris17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rangers Wars");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MineralYoi.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MineralYoi.setForeground(new java.awt.Color(255, 255, 255));
        MineralYoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MineralYoi.setText("999");
        MineralYoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(MineralYoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 90, -1));

        MineralShogun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MineralShogun.setForeground(new java.awt.Color(255, 255, 255));
        MineralShogun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MineralShogun.setText("999");
        MineralShogun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(MineralShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 90, -1));

        ARROWUP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrowUP.png"))); // NOI18N
        ARROWUP2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ARROWUP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 595, -1, -1));

        hargaShogun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        hargaShogun.setForeground(new java.awt.Color(255, 255, 0));
        hargaShogun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargaShogun.setText("99999");
        hargaShogun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hargaShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 645, 110, -1));

        lvlShogun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lvlShogun.setForeground(new java.awt.Color(255, 255, 255));
        lvlShogun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlShogun.setText("Level 999");
        lvlShogun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lvlShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 575, 110, -1));

        upShogun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol up.png"))); // NOI18N
        upShogun.setBorderPainted(false);
        upShogun.setContentAreaFilled(false);
        upShogun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upShogunActionPerformed(evt);
            }
        });
        getContentPane().add(upShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 560, -1, -1));

        dmgShogun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgShogun.setForeground(new java.awt.Color(255, 255, 255));
        dmgShogun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgShogun.setText("999");
        dmgShogun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 90, -1));

        hpShogun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        hpShogun.setForeground(new java.awt.Color(255, 255, 255));
        hpShogun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hpShogun.setText("999");
        hpShogun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hpShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 90, -1));

        ARROWUP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrowUP.png"))); // NOI18N
        ARROWUP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ARROWUP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 595, -1, -1));

        hargaYoimiya.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        hargaYoimiya.setForeground(new java.awt.Color(255, 255, 0));
        hargaYoimiya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargaYoimiya.setText("99999");
        hargaYoimiya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hargaYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 645, 110, -1));

        lvlYoimiya.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lvlYoimiya.setForeground(new java.awt.Color(255, 255, 255));
        lvlYoimiya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlYoimiya.setText("Level 999");
        lvlYoimiya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lvlYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 575, 110, -1));

        upYoimiya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol up.png"))); // NOI18N
        upYoimiya.setBorderPainted(false);
        upYoimiya.setContentAreaFilled(false);
        upYoimiya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upYoimiyaActionPerformed(evt);
            }
        });
        getContentPane().add(upYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        dmgYoimiya.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgYoimiya.setForeground(new java.awt.Color(255, 255, 255));
        dmgYoimiya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgYoimiya.setText("999");
        dmgYoimiya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 90, -1));

        hpYoimiya.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        hpYoimiya.setForeground(new java.awt.Color(255, 255, 255));
        hpYoimiya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hpYoimiya.setText("999");
        hpYoimiya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hpYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 90, -1));

        ARROWUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrowUP.png"))); // NOI18N
        ARROWUP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ARROWUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 595, -1, -1));

        hargaEris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        hargaEris.setForeground(new java.awt.Color(255, 255, 0));
        hargaEris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargaEris.setText("99999");
        hargaEris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hargaEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 645, 110, -1));

        lvlEris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lvlEris.setForeground(new java.awt.Color(255, 255, 255));
        lvlEris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlEris.setText("Level 999");
        lvlEris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lvlEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 575, 110, -1));

        upEris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol up.png"))); // NOI18N
        upEris.setBorderPainted(false);
        upEris.setContentAreaFilled(false);
        upEris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upErisActionPerformed(evt);
            }
        });
        getContentPane().add(upEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, -1, -1));

        dmgEris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris.setText("999");
        dmgEris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        hpEris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        hpEris.setForeground(new java.awt.Color(255, 255, 255));
        hpEris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hpEris.setText("999");
        hpEris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hpEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 90, -1));

        MineralEris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        MineralEris.setForeground(new java.awt.Color(255, 255, 255));
        MineralEris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MineralEris.setText("999");
        MineralEris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(MineralEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 90, -1));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol Back.png"))); // NOI18N
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        gold.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        gold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gold.setText("99999");
        getContentPane().add(gold, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 120, -1));

        user.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        user.setForeground(new java.awt.Color(153, 255, 153));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("User");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 250, -1));

        BgUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Upgrade Center BARU.jpg"))); // NOI18N
        getContentPane().add(BgUpgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dmgEris1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris1.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris1.setText("999");
        dmgEris1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris2.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris2.setText("999");
        dmgEris2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris3.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris3.setText("999");
        dmgEris3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris4.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris4.setText("999");
        dmgEris4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris5.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris5.setText("999");
        dmgEris5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris6.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris6.setText("999");
        dmgEris6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris7.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris7.setText("999");
        dmgEris7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris8.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris8.setText("999");
        dmgEris8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris9.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris9.setText("999");
        dmgEris9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris10.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris10.setText("999");
        dmgEris10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris11.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris11.setText("999");
        dmgEris11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris12.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris12.setText("999");
        dmgEris12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris13.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris13.setText("999");
        dmgEris13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris14.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris14.setText("999");
        dmgEris14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris15.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris15.setText("999");
        dmgEris15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris16.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris16.setText("999");
        dmgEris16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        dmgEris17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris17.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris17.setText("999");
        dmgEris17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        dispose();
        new Game(pemain,idx,player,kemute,keplay).setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void upErisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upErisActionPerformed
        if (curGold >= costEris){
            // Kurangi Gold + Update button
            curGold -= costEris;
            gold.setText(Integer.toString(curGold));
            int levelYoimiya = pemain.get(idx).getRanger()[1].getLevel();
            lvlYoimiya.setText("Level " + Integer.toString(levelYoimiya));
            costYoimiya = 5 + (levelYoimiya-1)*10;
            hargaYoimiya.setText(Integer.toString(costYoimiya));
            
            // Upgrade Status
            pemain.get(idx).getRanger()[1].setHp(pemain.get(idx).getRanger()[1].getHp() + 10);
            pemain.get(idx).getRanger()[1].setDmg(pemain.get(idx).getRanger()[1].getDmg() + 15);
            pemain.get(idx).getRanger()[1].setMineral(pemain.get(idx).getRanger()[1].getMineral() + 5);
            
            hpEris.setText(Integer.toString(pemain.get(idx).getRanger()[1].getHp()));
            dmgEris.setText(Integer.toString(pemain.get(idx).getRanger()[1].getDmg()));
        }
    }//GEN-LAST:event_upErisActionPerformed

    private void upYoimiyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upYoimiyaActionPerformed
        if (curGold >= costYoimiya){
            // Kurangi Gold + Update button
            curGold -= costYoimiya;
            gold.setText(Integer.toString(curGold));
            int levelEris = pemain.get(idx).getRanger()[0].getLevel() + 1;
            lvlEris.setText("Level " + Integer.toString(levelEris));
            costEris = 5 + (levelEris-1)*10;
            hargaEris.setText(Integer.toString(costEris));
            
            // Upgrade Status
            pemain.get(idx).getRanger()[0].setHp(pemain.get(idx).getRanger()[0].getHp() + 15);
            pemain.get(idx).getRanger()[0].setDmg(pemain.get(idx).getRanger()[0].getDmg() + 10);
            pemain.get(idx).getRanger()[0].setMineral(pemain.get(idx).getRanger()[0].getMineral() + 5);
            
            hpEris.setText(Integer.toString(pemain.get(idx).getRanger()[0].getHp()));
            dmgEris.setText(Integer.toString(pemain.get(idx).getRanger()[0].getDmg()));
        }
    }//GEN-LAST:event_upYoimiyaActionPerformed

    private void upShogunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upShogunActionPerformed
        if (curGold >= costShogun){
            // Kurangi Gold + Update button
            curGold -= costShogun;
            gold.setText(Integer.toString(curGold));
            int levelShogun = pemain.get(idx).getRanger()[2].getLevel();
            lvlShogun.setText("Level " + Integer.toString(levelShogun));
            costShogun = 5 + (levelShogun-1)*10;
            hargaShogun.setText(Integer.toString(costShogun));
            
            // Upgrade Status
            pemain.get(idx).getRanger()[2].setHp(pemain.get(idx).getRanger()[2].getHp() + 20);
            pemain.get(idx).getRanger()[2].setDmg(pemain.get(idx).getRanger()[2].getDmg() + 10);
            pemain.get(idx).getRanger()[2].setMineral(pemain.get(idx).getRanger()[2].getMineral() + 5);
            
            hpEris.setText(Integer.toString(pemain.get(idx).getRanger()[2].getHp()));
            dmgEris.setText(Integer.toString(pemain.get(idx).getRanger()[2].getDmg()));
        }
    }//GEN-LAST:event_upShogunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Upgrade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ARROWUP;
    private javax.swing.JLabel ARROWUP1;
    private javax.swing.JLabel ARROWUP2;
    private javax.swing.JButton Back;
    private javax.swing.JLabel BgUpgrade;
    private javax.swing.JLabel MineralEris;
    private javax.swing.JLabel MineralShogun;
    private javax.swing.JLabel MineralYoi;
    private javax.swing.JLabel dmgEris;
    private javax.swing.JLabel dmgEris1;
    private javax.swing.JLabel dmgEris10;
    private javax.swing.JLabel dmgEris11;
    private javax.swing.JLabel dmgEris12;
    private javax.swing.JLabel dmgEris13;
    private javax.swing.JLabel dmgEris14;
    private javax.swing.JLabel dmgEris15;
    private javax.swing.JLabel dmgEris16;
    private javax.swing.JLabel dmgEris17;
    private javax.swing.JLabel dmgEris2;
    private javax.swing.JLabel dmgEris3;
    private javax.swing.JLabel dmgEris4;
    private javax.swing.JLabel dmgEris5;
    private javax.swing.JLabel dmgEris6;
    private javax.swing.JLabel dmgEris7;
    private javax.swing.JLabel dmgEris8;
    private javax.swing.JLabel dmgEris9;
    private javax.swing.JLabel dmgShogun;
    private javax.swing.JLabel dmgYoimiya;
    private javax.swing.JLabel gold;
    private javax.swing.JLabel hargaEris;
    private javax.swing.JLabel hargaShogun;
    private javax.swing.JLabel hargaYoimiya;
    private javax.swing.JLabel hpEris;
    private javax.swing.JLabel hpShogun;
    private javax.swing.JLabel hpYoimiya;
    private javax.swing.JLabel lvlEris;
    private javax.swing.JLabel lvlShogun;
    private javax.swing.JLabel lvlYoimiya;
    private javax.swing.JButton upEris;
    private javax.swing.JButton upShogun;
    private javax.swing.JButton upYoimiya;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
