/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpbo;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Grady
 */
public class Upgrade extends javax.swing.JFrame {
    private Music btUpgrade = new Music("src\\music\\SoundUpgrade.wav");
    private Music btClick = new Music("src\\music\\buttonclick.wav");
    private Music player = null;
    private boolean kemute = false;
    private boolean keplay = false;
    
    private ArrayList<User> pemain = new ArrayList<>();
    private int idx;
    
    private int curGold;
    private int costEris;
    private int costYoimiya;
    private int costShogun;
    private int costTanjiro;
    private int costGojo;
    /**
     * Creates new form Upgrade
     */
    public Upgrade() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Upgrade(ArrayList<User> pemain,int idx, Music player, boolean kemute, boolean keplay) {
        this.player = player;
        this.kemute = kemute;
        this.keplay = keplay;
        
        this.pemain=pemain;
        this.idx=idx;
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.curGold = pemain.get(idx).getGold();
        gold.setText(Integer.toString(curGold));
        
        hpEris.setText(Integer.toString(pemain.get(idx).getRanger()[0].getHp()));
        dmgEris.setText(Integer.toString(pemain.get(idx).getRanger()[0].getDmg()));
        mineralEris.setText(Integer.toString(pemain.get(idx).getRanger()[0].getMineral()));
        int levelEris = pemain.get(idx).getRanger()[0].getLevel();
        lvlEris.setText("Level " + Integer.toString(levelEris));
        costEris = 5 + (levelEris-1)*10;
        hargaEris.setText(Integer.toString(costEris));
                
        hpYoimiya.setText(Integer.toString(pemain.get(idx).getRanger()[1].getHp()));
        dmgYoimiya.setText(Integer.toString(pemain.get(idx).getRanger()[1].getDmg()));
        mineralYoimiya.setText(Integer.toString(pemain.get(idx).getRanger()[1].getMineral()));
        int levelYoimiya = pemain.get(idx).getRanger()[1].getLevel();
        lvlYoimiya.setText("Level " + Integer.toString(levelYoimiya));
        costYoimiya = 5 + (levelYoimiya-1)*10;
        hargaYoimiya.setText(Integer.toString(costYoimiya));
        
        hpShogun.setText(Integer.toString(pemain.get(idx).getRanger()[2].getHp()));
        dmgShogun.setText(Integer.toString(pemain.get(idx).getRanger()[2].getDmg()));
        mineralShogun.setText(Integer.toString(pemain.get(idx).getRanger()[2].getMineral()));
        int levelShogun = pemain.get(idx).getRanger()[2].getLevel();
        lvlShogun.setText("Level " + Integer.toString(levelShogun));
        costShogun = 5 + (levelShogun-1)*10;
        hargaShogun.setText(Integer.toString(costShogun));
        
        hpTanjiro.setText(Integer.toString(pemain.get(idx).getRanger()[3].getHp()));
        dmgtTanjiro.setText(Integer.toString(pemain.get(idx).getRanger()[3].getDmg()));
        mineralTanjiro.setText(Integer.toString(pemain.get(idx).getRanger()[3].getMineral()));
        int levelTanjiro = pemain.get(idx).getRanger()[3].getLevel();
        lvlTanjiro.setText("Level " + Integer.toString(levelTanjiro));
        costTanjiro = 5 + (levelTanjiro-1)*10;
        hargaTanjiro.setText(Integer.toString(costTanjiro));
        
        hpGojo.setText(Integer.toString(pemain.get(idx).getRanger()[4].getHp()));
        dmgGojo.setText(Integer.toString(pemain.get(idx).getRanger()[4].getDmg()));
        mineralGojo.setText(Integer.toString(pemain.get(idx).getRanger()[4].getMineral()));
        int levelGojo = pemain.get(idx).getRanger()[4].getLevel();
        lvlGojo.setText("Level " + Integer.toString(levelGojo));
        costGojo = 5 + (levelGojo-1)*10;
        hargaGojo.setText(Integer.toString(costGojo));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hargaGojo = new javax.swing.JLabel();
        lvlGojo = new javax.swing.JLabel();
        upGojo = new javax.swing.JButton();
        mineralGojo = new javax.swing.JLabel();
        dmgGojo = new javax.swing.JLabel();
        hpGojo = new javax.swing.JLabel();
        hargaTanjiro = new javax.swing.JLabel();
        lvlTanjiro = new javax.swing.JLabel();
        upTanjiro = new javax.swing.JButton();
        mineralTanjiro = new javax.swing.JLabel();
        dmgtTanjiro = new javax.swing.JLabel();
        hpTanjiro = new javax.swing.JLabel();
        hargaShogun = new javax.swing.JLabel();
        lvlShogun = new javax.swing.JLabel();
        upShogun = new javax.swing.JButton();
        mineralShogun = new javax.swing.JLabel();
        dmgShogun = new javax.swing.JLabel();
        hpShogun = new javax.swing.JLabel();
        hargaYoimiya = new javax.swing.JLabel();
        lvlYoimiya = new javax.swing.JLabel();
        upYoimiya = new javax.swing.JButton();
        mineralYoimiya = new javax.swing.JLabel();
        dmgYoimiya = new javax.swing.JLabel();
        hpYoimiya = new javax.swing.JLabel();
        hargaEris = new javax.swing.JLabel();
        lvlEris = new javax.swing.JLabel();
        upEris = new javax.swing.JButton();
        mineralEris = new javax.swing.JLabel();
        dmgEris = new javax.swing.JLabel();
        hpEris = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        gold = new javax.swing.JLabel();
        BgUpgrade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rangers Wars");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hargaGojo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        hargaGojo.setForeground(new java.awt.Color(255, 255, 0));
        hargaGojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargaGojo.setText("99999");
        hargaGojo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hargaGojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1092, 640, 110, -1));

        lvlGojo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lvlGojo.setForeground(new java.awt.Color(255, 255, 255));
        lvlGojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlGojo.setText("Level 999");
        lvlGojo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lvlGojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1091, 575, 110, -1));

        upGojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol up.png"))); // NOI18N
        upGojo.setBorderPainted(false);
        upGojo.setContentAreaFilled(false);
        upGojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upGojoActionPerformed(evt);
            }
        });
        getContentPane().add(upGojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 560, -1, -1));

        mineralGojo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        mineralGojo.setForeground(new java.awt.Color(255, 255, 255));
        mineralGojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mineralGojo.setText("999");
        mineralGojo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mineralGojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 510, 90, -1));

        dmgGojo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgGojo.setForeground(new java.awt.Color(255, 255, 255));
        dmgGojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgGojo.setText("999");
        dmgGojo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgGojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 455, 90, -1));

        hpGojo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        hpGojo.setForeground(new java.awt.Color(255, 255, 255));
        hpGojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hpGojo.setText("999");
        hpGojo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hpGojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 400, 90, -1));

        hargaTanjiro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        hargaTanjiro.setForeground(new java.awt.Color(255, 255, 0));
        hargaTanjiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargaTanjiro.setText("99999");
        hargaTanjiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hargaTanjiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 640, 110, -1));

        lvlTanjiro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lvlTanjiro.setForeground(new java.awt.Color(255, 255, 255));
        lvlTanjiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlTanjiro.setText("Level 999");
        lvlTanjiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lvlTanjiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 575, 110, -1));

        upTanjiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol up.png"))); // NOI18N
        upTanjiro.setBorderPainted(false);
        upTanjiro.setContentAreaFilled(false);
        upTanjiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upTanjiroActionPerformed(evt);
            }
        });
        getContentPane().add(upTanjiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, -1, -1));

        mineralTanjiro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        mineralTanjiro.setForeground(new java.awt.Color(255, 255, 255));
        mineralTanjiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mineralTanjiro.setText("999");
        mineralTanjiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mineralTanjiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, 90, -1));

        dmgtTanjiro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgtTanjiro.setForeground(new java.awt.Color(255, 255, 255));
        dmgtTanjiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgtTanjiro.setText("999");
        dmgtTanjiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgtTanjiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 455, 90, -1));

        hpTanjiro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        hpTanjiro.setForeground(new java.awt.Color(255, 255, 255));
        hpTanjiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hpTanjiro.setText("999");
        hpTanjiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hpTanjiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 90, -1));

        hargaShogun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        hargaShogun.setForeground(new java.awt.Color(255, 255, 0));
        hargaShogun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargaShogun.setText("99999");
        hargaShogun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hargaShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 645, 110, -1));

        lvlShogun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lvlShogun.setForeground(new java.awt.Color(255, 255, 255));
        lvlShogun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlShogun.setText("Level 999");
        lvlShogun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lvlShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 575, 110, -1));

        upShogun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol up.png"))); // NOI18N
        upShogun.setBorderPainted(false);
        upShogun.setContentAreaFilled(false);
        upShogun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upShogunActionPerformed(evt);
            }
        });
        getContentPane().add(upShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 560, -1, -1));

        mineralShogun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        mineralShogun.setForeground(new java.awt.Color(255, 255, 255));
        mineralShogun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mineralShogun.setText("999");
        mineralShogun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mineralShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 90, -1));

        dmgShogun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgShogun.setForeground(new java.awt.Color(255, 255, 255));
        dmgShogun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgShogun.setText("999");
        dmgShogun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 455, 90, -1));

        hpShogun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        hpShogun.setForeground(new java.awt.Color(255, 255, 255));
        hpShogun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hpShogun.setText("999");
        hpShogun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hpShogun, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 90, -1));

        hargaYoimiya.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        hargaYoimiya.setForeground(new java.awt.Color(255, 255, 0));
        hargaYoimiya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargaYoimiya.setText("99999");
        hargaYoimiya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hargaYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 648, 110, -1));

        lvlYoimiya.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lvlYoimiya.setForeground(new java.awt.Color(255, 255, 255));
        lvlYoimiya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlYoimiya.setText("Level 999");
        lvlYoimiya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lvlYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 110, -1));

        upYoimiya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol up.png"))); // NOI18N
        upYoimiya.setBorderPainted(false);
        upYoimiya.setContentAreaFilled(false);
        upYoimiya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upYoimiyaActionPerformed(evt);
            }
        });
        getContentPane().add(upYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 565, -1, -1));

        mineralYoimiya.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        mineralYoimiya.setForeground(new java.awt.Color(255, 255, 255));
        mineralYoimiya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mineralYoimiya.setText("999");
        mineralYoimiya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mineralYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 90, -1));

        dmgYoimiya.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgYoimiya.setForeground(new java.awt.Color(255, 255, 255));
        dmgYoimiya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgYoimiya.setText("999");
        dmgYoimiya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 455, 90, -1));

        hpYoimiya.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        hpYoimiya.setForeground(new java.awt.Color(255, 255, 255));
        hpYoimiya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hpYoimiya.setText("999");
        hpYoimiya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hpYoimiya, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 90, -1));

        hargaEris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        hargaEris.setForeground(new java.awt.Color(255, 255, 0));
        hargaEris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargaEris.setText("99999");
        hargaEris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hargaEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 645, 110, -1));

        lvlEris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lvlEris.setForeground(new java.awt.Color(255, 255, 255));
        lvlEris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lvlEris.setText("Level 999");
        lvlEris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lvlEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 575, 110, -1));

        upEris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol up.png"))); // NOI18N
        upEris.setBorderPainted(false);
        upEris.setContentAreaFilled(false);
        upEris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upErisActionPerformed(evt);
            }
        });
        getContentPane().add(upEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, -1, -1));

        mineralEris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        mineralEris.setForeground(new java.awt.Color(255, 255, 255));
        mineralEris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mineralEris.setText("999");
        mineralEris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(mineralEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 90, -1));

        dmgEris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dmgEris.setForeground(new java.awt.Color(255, 255, 255));
        dmgEris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dmgEris.setText("999");
        dmgEris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dmgEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 455, 90, -1));

        hpEris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        hpEris.setForeground(new java.awt.Color(255, 255, 255));
        hpEris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hpEris.setText("999");
        hpEris.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hpEris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 90, -1));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tombol Back.png"))); // NOI18N
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        gold.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        gold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gold.setText("99999");
        getContentPane().add(gold, new org.netbeans.lib.awtextra.AbsoluteConstraints(1123, 25, 120, -1));

        BgUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Upgrade Center BARU.jpg"))); // NOI18N
        getContentPane().add(BgUpgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        try {            
            FileOutputStream save = new FileOutputStream(System.getProperty("user.dir") + "\\users.ser");
            ObjectOutputStream out = new ObjectOutputStream(save);
            out.writeObject(this.pemain);
            out.close();
            save.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "failed");
        }
        dispose();
        new Game(pemain,idx,player,kemute,keplay).setVisible(true);
        if (!kemute)
            btClick.Clip().start();
    }//GEN-LAST:event_BackActionPerformed

    private void upErisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upErisActionPerformed
        if (curGold >= costEris){
            // Kurangi Gold + Update button
            curGold -= costEris;
            pemain.get(idx).setGold(curGold);
            gold.setText(Integer.toString(curGold));
            int levelEris = pemain.get(idx).getRanger()[0].getLevel() + 1;
            pemain.get(idx).getRanger()[0].setLevel(levelEris);
            lvlEris.setText("Level " + Integer.toString(levelEris));
            costEris = 5 + (levelEris-1)*10;
            hargaEris.setText(Integer.toString(costEris));
            
            // Upgrade Status
            pemain.get(idx).getRanger()[0].setHp(pemain.get(idx).getRanger()[0].getHp() + 15);
            pemain.get(idx).getRanger()[0].setDmg(pemain.get(idx).getRanger()[0].getDmg() + 15);
            pemain.get(idx).getRanger()[0].setMineral(pemain.get(idx).getRanger()[0].getMineral() + 5);
            
            hpEris.setText(Integer.toString(pemain.get(idx).getRanger()[0].getHp()));
            dmgEris.setText(Integer.toString(pemain.get(idx).getRanger()[0].getDmg()));
            mineralEris.setText(Integer.toString(pemain.get(idx).getRanger()[0].getMineral()));
            // Sound Effect
            if (!kemute){
                btUpgrade = new Music("src\\music\\SoundUpgrade.wav");
                btUpgrade.Clip().start();
            }
        }
    }//GEN-LAST:event_upErisActionPerformed

    private void upYoimiyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upYoimiyaActionPerformed
        if (curGold >= costYoimiya){
            // Kurangi Gold + Update button
            curGold -= costYoimiya;
            pemain.get(idx).setGold(curGold);
            gold.setText(Integer.toString(curGold));
            int levelYoimiya = pemain.get(idx).getRanger()[1].getLevel() + 1;
            pemain.get(idx).getRanger()[1].setLevel(levelYoimiya);
            lvlYoimiya.setText("Level " + Integer.toString(levelYoimiya));
            costYoimiya = 5 + (levelYoimiya-1)*10;
            hargaYoimiya.setText(Integer.toString(costYoimiya));
            
            // Upgrade Status
            pemain.get(idx).getRanger()[1].setHp(pemain.get(idx).getRanger()[1].getHp() + 5);
            pemain.get(idx).getRanger()[1].setDmg(pemain.get(idx).getRanger()[1].getDmg() + 25);
            pemain.get(idx).getRanger()[1].setMineral(pemain.get(idx).getRanger()[1].getMineral() + 5);
            
            hpYoimiya.setText(Integer.toString(pemain.get(idx).getRanger()[1].getHp()));
            dmgYoimiya.setText(Integer.toString(pemain.get(idx).getRanger()[1].getDmg()));
            mineralYoimiya.setText(Integer.toString(pemain.get(idx).getRanger()[1].getMineral()));
            // Sound Effect
            if (!kemute){
                btUpgrade = new Music("src\\music\\SoundUpgrade.wav");
                btUpgrade.Clip().start();
            }
        }
    }//GEN-LAST:event_upYoimiyaActionPerformed

    private void upShogunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upShogunActionPerformed
        if (curGold >= costShogun){
            // Kurangi Gold + Update button
            curGold -= costShogun;
            pemain.get(idx).setGold(curGold);
            gold.setText(Integer.toString(curGold));
            int levelShogun = pemain.get(idx).getRanger()[2].getLevel() + 1;
            pemain.get(idx).getRanger()[2].setLevel(levelShogun);
            lvlShogun.setText("Level " + Integer.toString(levelShogun));
            costShogun = 5 + (levelShogun-1)*10;
            hargaShogun.setText(Integer.toString(costShogun));
            
            // Upgrade Status
            pemain.get(idx).getRanger()[2].setHp(pemain.get(idx).getRanger()[2].getHp() + 10);
            pemain.get(idx).getRanger()[2].setDmg(pemain.get(idx).getRanger()[2].getDmg() + 20);
            pemain.get(idx).getRanger()[2].setMineral(pemain.get(idx).getRanger()[2].getMineral() + 5);
            
            hpShogun.setText(Integer.toString(pemain.get(idx).getRanger()[2].getHp()));
            dmgShogun.setText(Integer.toString(pemain.get(idx).getRanger()[2].getDmg()));
            mineralShogun.setText(Integer.toString(pemain.get(idx).getRanger()[2].getMineral()));
            // Sound Effect
            if (!kemute){
                btUpgrade = new Music("src\\music\\SoundUpgrade.wav");
                btUpgrade.Clip().start();
            }
        }
    }//GEN-LAST:event_upShogunActionPerformed

    private void upTanjiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upTanjiroActionPerformed
        if (curGold >= costTanjiro){
            // Kurangi Gold + Update button
            curGold -= costTanjiro;
            pemain.get(idx).setGold(curGold);
            gold.setText(Integer.toString(curGold));
            int levelTanjiro = pemain.get(idx).getRanger()[3].getLevel() + 1;
            pemain.get(idx).getRanger()[3].setLevel(levelTanjiro);
            lvlTanjiro.setText("Level " + Integer.toString(levelTanjiro));
            costTanjiro = 5 + (levelTanjiro-1)*10;
            hargaTanjiro.setText(Integer.toString(costTanjiro));
            
            // Upgrade Status
            pemain.get(idx).getRanger()[3].setHp(pemain.get(idx).getRanger()[3].getHp() + 25);
            pemain.get(idx).getRanger()[3].setDmg(pemain.get(idx).getRanger()[3].getDmg() + 5);
            pemain.get(idx).getRanger()[3].setMineral(pemain.get(idx).getRanger()[3].getMineral() + 5);
            
            hpTanjiro.setText(Integer.toString(pemain.get(idx).getRanger()[3].getHp()));
            dmgtTanjiro.setText(Integer.toString(pemain.get(idx).getRanger()[3].getDmg()));
            mineralTanjiro.setText(Integer.toString(pemain.get(idx).getRanger()[3].getMineral()));
            // Sound Effect
            if (!kemute){
                btUpgrade = new Music("src\\music\\SoundUpgrade.wav");
                btUpgrade.Clip().start();
            }
        }
    }//GEN-LAST:event_upTanjiroActionPerformed

    private void upGojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upGojoActionPerformed
        if (curGold >= costGojo){
            // Kurangi Gold + Update button
            curGold -= costGojo;
            pemain.get(idx).setGold(curGold);
            gold.setText(Integer.toString(curGold));
            int levelGojo = pemain.get(idx).getRanger()[4].getLevel() + 1;
            pemain.get(idx).getRanger()[4].setLevel(levelGojo);
            lvlGojo.setText("Level " + Integer.toString(levelGojo));
            costGojo = 5 + (levelGojo-1)*10;
            hargaGojo.setText(Integer.toString(costGojo));
            
            // Upgrade Status
            pemain.get(idx).getRanger()[4].setHp(pemain.get(idx).getRanger()[4].getHp() + 20);
            pemain.get(idx).getRanger()[4].setDmg(pemain.get(idx).getRanger()[4].getDmg() + 10);
            pemain.get(idx).getRanger()[4].setMineral(pemain.get(idx).getRanger()[4].getMineral() + 5);
            
            hpGojo.setText(Integer.toString(pemain.get(idx).getRanger()[4].getHp()));
            dmgGojo.setText(Integer.toString(pemain.get(idx).getRanger()[4].getDmg()));
            mineralGojo.setText(Integer.toString(pemain.get(idx).getRanger()[4].getMineral()));
            // Sound Effect
            if (!kemute){
                btUpgrade = new Music("src\\music\\SoundUpgrade.wav");
                btUpgrade.Clip().start();
            }
        }
    }//GEN-LAST:event_upGojoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Upgrade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel BgUpgrade;
    private javax.swing.JLabel dmgEris;
    private javax.swing.JLabel dmgGojo;
    private javax.swing.JLabel dmgShogun;
    private javax.swing.JLabel dmgYoimiya;
    private javax.swing.JLabel dmgtTanjiro;
    private javax.swing.JLabel gold;
    private javax.swing.JLabel hargaEris;
    private javax.swing.JLabel hargaGojo;
    private javax.swing.JLabel hargaShogun;
    private javax.swing.JLabel hargaTanjiro;
    private javax.swing.JLabel hargaYoimiya;
    private javax.swing.JLabel hpEris;
    private javax.swing.JLabel hpGojo;
    private javax.swing.JLabel hpShogun;
    private javax.swing.JLabel hpTanjiro;
    private javax.swing.JLabel hpYoimiya;
    private javax.swing.JLabel lvlEris;
    private javax.swing.JLabel lvlGojo;
    private javax.swing.JLabel lvlShogun;
    private javax.swing.JLabel lvlTanjiro;
    private javax.swing.JLabel lvlYoimiya;
    private javax.swing.JLabel mineralEris;
    private javax.swing.JLabel mineralGojo;
    private javax.swing.JLabel mineralShogun;
    private javax.swing.JLabel mineralTanjiro;
    private javax.swing.JLabel mineralYoimiya;
    private javax.swing.JButton upEris;
    private javax.swing.JButton upGojo;
    private javax.swing.JButton upShogun;
    private javax.swing.JButton upTanjiro;
    private javax.swing.JButton upYoimiya;
    // End of variables declaration//GEN-END:variables
}
